language: node_js
sudo: required
node_js: 
  - 7.9.0

cache:
  directories:
    - node_modules

branches:
  only:
  - dev

before_install:
- npm install hexo-cli -g --no-optional
- npm install hexo-deployer-git --save

install:
- npm install

before_script:
- git config --global user.name "LinLshare"
- git config --global user.email "linlshare@gmail.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
- hexo clean

after_script:
- hexo g -d

notifications:
  webhooks:
    urls:
      - https://us-central1-blog-3d4cb.cloudfunctions.net/travisPush
    on_success: always # default: always
    on_failure: never # default: always
    on_start:   never # default: never
    on_cancel:  never # default: always
    on_error:   never # default: always